language: ruby
rvm:
- 2.2
deploy:
  provider: rubygems
  api_key: YOUR API KEY
  on:
    tags: true
install:
- chmod 777 ./bin/install.sh
- "./bin/install.sh"
- BUNDLE_GEMFILE=gemfile bundle install
- rake db:create db:migrate
script: rspec spec
before_install:
- openssl aes-256-cbc -K $encrypted_27eb8f448067_key -iv $encrypted_27eb8f448067_iv
  -in deploy-key.enc -out deploy-key -d
