language: ruby
rvm:
- 2.2

addons:
  ssh_known_hosts: ubuntu

before_install:
- openssl aes-256-cbc -K $encrypted_27eb8f448067_key -iv $encrypted_27eb8f448067_iv
  -in deploy-key.enc -out deploy-key -d

install:
  - bash ./bin/install.sh

script: rspec spec

after_success:
  - bash ./bin/deploy.sh

notifications:
  webhooks:
    urls:
      - http://162.243.166.146:9000/hooks/redeploy-webhook
    on_failure: never
    on_success: always
