language: ruby
rvm:
- 2.2
addons:
  ssh_known_hosts: ubuntu

deploy:
  provider: rubygems
  api_key: YOUR API KEY
  on:
    tags: true

before_install:
- openssl aes-256-cbc -K $encrypted_0f0be8abb7f5_key -iv $encrypted_0f0be8abb7f5_iv -in deploy-key.enc -out deploy-key -d

install:
  - bash /bin/install.sh

script: rspec spec

after_success:
  - bash bin/deploy.sh
