language: ruby
rvm:
 - 2.2

deploy:
  provider: rubygems
  api_key: "YOUR API KEY"
  on:
    tags: true

install:
  - chmod 777 ./bin/install.sh
  - ./bin/install.sh
  - BUNDLE_GEMFILE=gemfile bundle install

script: rspec spec
